/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesCategoryIdIndexRouteImport } from './routes/categories/$categoryId/index'
import { Route as CategoriesCategoryIdArticleIdRouteImport } from './routes/categories/$categoryId/$articleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdIndexRoute =
  CategoriesCategoryIdIndexRouteImport.update({
    id: '/categories/$categoryId/',
    path: '/categories/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesCategoryIdArticleIdRoute =
  CategoriesCategoryIdArticleIdRouteImport.update({
    id: '/categories/$categoryId/$articleId',
    path: '/categories/$categoryId/$articleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories/$categoryId/$articleId': typeof CategoriesCategoryIdArticleIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$categoryId/$articleId': typeof CategoriesCategoryIdArticleIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories/$categoryId/$articleId': typeof CategoriesCategoryIdArticleIdRoute
  '/categories/$categoryId/': typeof CategoriesCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories/$categoryId/$articleId'
    | '/categories/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories/$categoryId/$articleId' | '/categories/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/categories/$categoryId/$articleId'
    | '/categories/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesCategoryIdArticleIdRoute: typeof CategoriesCategoryIdArticleIdRoute
  CategoriesCategoryIdIndexRoute: typeof CategoriesCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/': {
      id: '/categories/$categoryId/'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/$articleId': {
      id: '/categories/$categoryId/$articleId'
      path: '/categories/$categoryId/$articleId'
      fullPath: '/categories/$categoryId/$articleId'
      preLoaderRoute: typeof CategoriesCategoryIdArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesCategoryIdArticleIdRoute: CategoriesCategoryIdArticleIdRoute,
  CategoriesCategoryIdIndexRoute: CategoriesCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
