/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportHelpRouteImport } from './routes/support/help'
import { Route as AuthWelcomeRouteImport } from './routes/auth/welcome'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthAddtaxformRouteImport } from './routes/auth/addtaxform'
import { Route as CategoriesCategoryIdIndexRouteImport } from './routes/categories/$categoryId/index'
import { Route as CategoriesCategoryIdArticleIdRouteImport } from './routes/categories/$categoryId/$articleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportHelpRoute = SupportHelpRouteImport.update({
  id: '/support/help',
  path: '/support/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/auth/welcome',
  path: '/auth/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAddtaxformRoute = AuthAddtaxformRouteImport.update({
  id: '/auth/addtaxform',
  path: '/auth/addtaxform',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdIndexRoute =
  CategoriesCategoryIdIndexRouteImport.update({
    id: '/categories/$categoryId/',
    path: '/categories/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesCategoryIdArticleIdRoute =
  CategoriesCategoryIdArticleIdRouteImport.update({
    id: '/categories/$categoryId/$articleId',
    path: '/categories/$categoryId/$articleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/addtaxform': typeof AuthAddtaxformRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/support/help': typeof SupportHelpRoute
  '/categories/$categoryId/$articleId': typeof CategoriesCategoryIdArticleIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/addtaxform': typeof AuthAddtaxformRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/support/help': typeof SupportHelpRoute
  '/categories/$categoryId/$articleId': typeof CategoriesCategoryIdArticleIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/addtaxform': typeof AuthAddtaxformRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/support/help': typeof SupportHelpRoute
  '/categories/$categoryId/$articleId': typeof CategoriesCategoryIdArticleIdRoute
  '/categories/$categoryId/': typeof CategoriesCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/addtaxform'
    | '/auth/login'
    | '/auth/welcome'
    | '/support/help'
    | '/categories/$categoryId/$articleId'
    | '/categories/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/addtaxform'
    | '/auth/login'
    | '/auth/welcome'
    | '/support/help'
    | '/categories/$categoryId/$articleId'
    | '/categories/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/auth/addtaxform'
    | '/auth/login'
    | '/auth/welcome'
    | '/support/help'
    | '/categories/$categoryId/$articleId'
    | '/categories/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthAddtaxformRoute: typeof AuthAddtaxformRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
  SupportHelpRoute: typeof SupportHelpRoute
  CategoriesCategoryIdArticleIdRoute: typeof CategoriesCategoryIdArticleIdRoute
  CategoriesCategoryIdIndexRoute: typeof CategoriesCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/help': {
      id: '/support/help'
      path: '/support/help'
      fullPath: '/support/help'
      preLoaderRoute: typeof SupportHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/welcome': {
      id: '/auth/welcome'
      path: '/auth/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/addtaxform': {
      id: '/auth/addtaxform'
      path: '/auth/addtaxform'
      fullPath: '/auth/addtaxform'
      preLoaderRoute: typeof AuthAddtaxformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/': {
      id: '/categories/$categoryId/'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/$articleId': {
      id: '/categories/$categoryId/$articleId'
      path: '/categories/$categoryId/$articleId'
      fullPath: '/categories/$categoryId/$articleId'
      preLoaderRoute: typeof CategoriesCategoryIdArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthAddtaxformRoute: AuthAddtaxformRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
  SupportHelpRoute: SupportHelpRoute,
  CategoriesCategoryIdArticleIdRoute: CategoriesCategoryIdArticleIdRoute,
  CategoriesCategoryIdIndexRoute: CategoriesCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
